project:
  type: website

website:
  title: "Dhruv's Website"
  page-navigation: true
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts
      - href: projects
        text: Projects
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/ddole-net
#      - icon: twitter
#        href: https://twitter.com
  sidebar:
    title: "Projects"
    style: "docked"
    search: false
    contents: 
      - auto: projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



