project:
  type: website

website:
  title: "Dhruv's Website"
  page-navigation: true
  twitter-card: true
  open-graph: true
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts
      - href: projects
        text: Projects
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/ddole-net

  sidebar:
    id: "projects"
    title: "Projects"
    style: "docked"
    search: false
    contents: 
      - auto: projects/
      # - text: 3D Printing
      #   href: projects/3d-printing/
      # - text: Wildfire Predictions
      #   href: projects/wildfire-predictions/
      # - text: The Money Project
      #   href: projects/money/
      # - text: Self-Hosting
      #   href: projects/selfhosting
      
theme:
  light: simplex
  # dark: [simplex, dark-mode.scss]

format:
  html:
    smooth-scroll: false
#     theme:
#       - cosmo
#       - brand
#     css: styles.css



