[project]
name = "website"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "deltalake>=0.25.5",
    "dotenv>=0.9.9",
    "minio>=7.2.15",
    "notebook>=7.4.0",
    "polars>=1.27.1",
    "pyarrow>=19.0.1",
]
