---
title: Roadmap
---

1. Make this documentation up-to-date
2. Create new node structure
3. Setup BTRBK backups
4. Consolidate VPSs
5. Setup Netbird backups by system
6. Disable Password SSH, 
7. Create `dhruv` sudo user on all machines
8. Distribute my SSH key & move all ssh to 2222
**WROTE ANSIBLE PLAYBOOKS FOR UPDATES, SSH CONFIG, USERS, KEYS**
9. Firewall Lockdown and Netbird ACLs
10. Figure out how to disable snat on netbird routers **STUCK**(SKIPPING)
11. Disable stub-resolvers on docker nodes
12. Catalog all Nodes, Services in Excel, Subscribe to github releases for services
13. Deploy Monitoring Stack
14. Authentik LDAP
15. Create proper USER/GROUP/POLICIES
16. Randomize service admin passwords
17. Metrics and Logs
18. Set up a Host Runner with docker and all necessary tools
HERE
19. Deploy Data Stack
20. Calibre Web SSO
21. Setup Nvidia GPU on dkr-01
22. Rebuild dkr-03/4: Make 4 the public
23. Final Audit: Local systems, applications, cloud services: Traffic through nginx, TLS, monitored, SSO, passwords randomized, Source IP tracking, backed up
24. Operational!
