---
title: Network
---

## Design Considerations

This network is designed to be as simple as possible, while allowing access separation across what I am calling ***Service Access Zones***. Basically I want the following access rules:

-   Public clients Will only have access to services and hosts on public VPSs

-   Trusted clients(on wifi and vpn) should be able to access public and trusted services and hosts

-   I should have unrestricted access to all services and hosts.

::: callout-note
See [Service Access Zones](./access-zones.qmd) for further thoughts on network access control.
:::

The only two services that are publicly reachable are Netbird and Authentik(hosted on a cloud VPS). Since these are publicly reachable, users of other internal sites can authenticate to the vpn and then access the rest of the network. This removes the need for a tunnel, and removes one attack vector.

The table below has details for the whole network:

### Network Table

| Name | Type | VLAN ID | Subnet | DHCP | Purpose |
|------------|------------|------------|------------|------------|------------|
| Native | VLAN | 1 | 10.0.0.0/24 | True | Proxmox Nodes |
| Internal | VLAN | 10 | 10.0.10.0/24 | True | Internal lab nodes |
| Trusted | VLAN | 20 | 10.0.20.0/24 | False | Nodes accessible to trusted clients (wifi and Netbird) |
| Wifi | VLAN | 40 | 10.0.40.0/24 | True | Home WiFi |
| Netbird | VPN | N/A | 100.64.0.0/10 | N/A | Mesh overlay for p2p connections. |

### Network Diagram

!INSERT MERMAID DIAGRAM HERE!

## Remote Access

Secure remote access and sharing with friends and family is an annoying problem without a public IP. The two major options are tunnels, and meshes. All the notes below are in the context of bypassing CGNAT. I am also trying to avoid relaying traffic through a Cloud VPS: I'll probably quickly hit bandwidth limits.

#### Tunnels:

-   WireGuard: Easy to make a single tunnel, harder to manage multiple, can't traverse NAT by itself

-   Cloudflare Tunnel: Free, terminates TLS at edge server, has request limits

-   ngrok: IDK anything about it, other than its not entirely free

-   zrok: selfhosted ngrok built on OpenZiti. You'll have to pay for bandwidth on a cloud VPS

#### VPN:

-   WireGuard: Requires a cloud "hub" server to route traffic: bandwidth is expensive

-   OpenVPN: same as Wireguard, old, slow

-   Tailscale: Manages a WireGuard peer-to-peer(p2p) mesh. Works amazingly, Is free for 3 users, has an affordable 6 user plan, Client software works great! If cloud relay is required, its free.

-   Headscale: Open source implementation of Tailscale's controlplane. Very simple to set up, basic features work well, uses Tailscale clients, doesn't integrate that well with SSO based ACLs: cloud relay can be disabled.

-   Netbird: Open source WireGuard mesh control plane: little more complicated than headscale, docs kinda suck, seems to work pretty well, can get users and groups from OIDC SSO. Has a great ClickOps policy management system.

I used Tailscale for a while but wanted more users so I tried Headscale. Headscale has a very limited set of controlplane features so I tried Netbird out and it works great for me so that's what I'm using.