name: Build and Deploy Quarto Site to S3
on:
  push:
    branches: main

jobs:
  deploy:
    name: python
    runs-on: docker
    container:
      image: "code.ddole.net/homelab/actions-image:latest"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"

      - name: Set up Python
        run: uv python install

      - name: Install the Project
        run: uv sync --all-extras --dev

      - name: Render site
        run: |
          quarto render

      - name: Copy files to S3
        run: |
          aws s3 sync _site/ s3://ddole.net